# -*- mode: dockerfile; -*- vim: set ft=dockerfile:
FROM alpine:3.22.0 AS scratch
WORKDIR /scratch
# Copy these env variables to the next container too
ENV CARTO_VERSION 5.9.0
ENV MOD_TILE_VERSION 0.8.1
ADD https://github.com/gravitystorm/openstreetmap-carto/archive/refs/tags/v${CARTO_VERSION}.tar.gz openstreetmap-carto-${CARTO_VERSION}.tar.gz
ADD https://github.com/openstreetmap/mod_tile/archive/refs/tags/v${MOD_TILE_VERSION}.tar.gz mod_tile-${MOD_TILE_VERSION}.tar.gz
# ADD https://download.geofabrik.de/europe/monaco-latest.osm.pbf monaco-latest.osm.pbf
# ADD https://download.geofabrik.de/europe/monaco-latest.osm.pbf.md5 monaco-latest.osm.pbf.md5
# ADD https://download.geofabrik.de/europe/monaco.poly monaco.poly
RUN tar -xf openstreetmap-carto-${CARTO_VERSION}.tar.gz \
    && tar -xf mod_tile-${MOD_TILE_VERSION}.tar.gz

FROM docker.io/postgres:15.13-bookworm
LABEL uk.co.fdsd.tripserver.postgis.version="@PACKAGE_VERSION@"

ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.3.2+dfsg-1+b1
ENV POSTGIS_SCRIPTS_VERSION 3.3.2+dfsg-1
RUN apt-get update \
    && apt-get full-upgrade --yes --allow-change-held-packages \
    && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR
RUN apt-get install -y --no-install-recommends \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_SCRIPTS_VERSION \
    procps locales coreutils \
#    tar xz-utils ca-certificates tzdata \
    apache2 libapache2-mod-tile renderd openstreetmap-carto sudo \
    fonts-hanazono \
    fonts-noto-extra \
    python3-yaml python3-psycopg2 \
#    node-carto osm2pgsql \
    libjs-leaflet \
    && rm -rf /var/lib/apt/lists/*
ENV POSTGRES_USER _renderd
ENV POSTGRES_DB gis
RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen \
    # && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    # && sed -i -e 's/# es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen \
    # && sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8 \
    && update-locale LANG LANGUAGE
    # && ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && \
    # && dpkg-reconfigure tzdata
ENV LANG en_GB.utf8
# ENV LC_ALL ${LANG}

RUN mkdir /var/www/example-map
ENV CARTO_VERSION 5.9.0
ENV MOD_TILE_VERSION 0.8.1
COPY --from=scratch /scratch/openstreetmap-carto-${CARTO_VERSION}/patterns /usr/share/openstreetmap-carto-common/patterns/
COPY --from=scratch /scratch/mod_tile-${MOD_TILE_VERSION}/utils/example-map/index.html /var/www/example-map/
COPY provisioning/apache2/etc-apache2-conf-available-renderd.conf /etc/apache2/conf-available/renderd.conf
RUN ln -s /usr/share/javascript/leaflet /var/www/example-map/leaflet

RUN mkdir -p /run/renderd \
    && chown _renderd:_renderd /run/renderd

RUN set -eux; \
    echo '[ajt]\n\
URI=/tile/\n\
TILEDIR=/var/cache/renderd/tiles\n\
XML=/usr/share/openstreetmap-carto-common/style.xml\n\
HOST=localhost\n\
TILESIZE=256\n\
MAXZOOM=20' >> /etc/renderd.conf \
    && sed -i 's,/usr/share/fonts/truetype,/usr/share/fonts,g' /etc/renderd.conf \
    && sed -i -e 's~http://localhost:8081/tiles/renderd-example~/tile~' \
    -e 's/maxZoom: 12/maxZoom: 20/' \
    -e 's~var layerControl~// var layerControl~' \
    /var/www/example-map/index.html \
    && sed -i -e 's~<Font face-name="Noto Emoji Regular" />~~g' \
    -e 's~<Font face-name="Noto Emoji Bold" />~~g' \
    /usr/share/openstreetmap-carto-common/style.xml

RUN a2enmod tile headers
RUN a2enconf renderd

WORKDIR /downloads
# gis.dmp is a pg_dump of the gis database after importing a map.  It can be
# copied from a previous version of the container:
#
#     $ docker run --rm -p 8080:80 --name tile-server -d fdean/tile-server
#     $ docker cp tile-server:/downloads/gis.dmp provisioning/downloads/
#
# Alternatively, after import, run the map container, e.g.:
#
#     $ docker run -p 8080:80 --rm --name osm \
#       -v osm-data:/data/database/ \
#       -v osm-tiles:/data/tiles/ \
#       -v $(pwd)/provisioning/downloads:/backup \
#       -d overv/openstreetmap-tile-server:2.3.0 run
#
# connect to the running container:
#
#     $ docker exec -it osm bash
#
# dump the database contents using the default password:
#
#     $ docker exec --env=PGPASSWORD=renderer -it osm \
#       pg_dump --no-owner --format=c -h localhost -U renderer \
#       -f /backup/gis.dmp gis
#
COPY provisioning/downloads/gis.dmp .

WORKDIR /docker-entrypoint-initdb.d
COPY provisioning/schema/11_init-gis-db.sh .
COPY provisioning/docker/tile_server_run.sh /

ENTRYPOINT ["/tile_server_run.sh"]

STOPSIGNAL SIGINT

CMD ["postgres"]

EXPOSE 80
