GRANT CONNECT ON DATABASE trip  TO trip_role;
GRANT SELECT, INSERT ON role TO trip_role;
GRANT SELECT, INSERT ON location TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_route TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_route_point TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_sharing TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_track TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_track_point TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_track_segment TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON itinerary_waypoint TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON location_sharing TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON tile TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_role TO trip_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON usertable TO trip_role;
GRANT SELECT, INSERT ON tile_metric TO trip_role;
GRANT SELECT ON georef_format TO trip_role;
GRANT SELECT ON path_color TO trip_role;
GRANT SELECT ON waypoint_symbol TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_route_point_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_route_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_track_point_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_track_segment_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_track_seq TO trip_role;
GRANT USAGE ON SEQUENCE itinerary_waypoint_seq TO trip_role;
GRANT USAGE ON SEQUENCE location_seq TO trip_role;
GRANT USAGE ON SEQUENCE role_seq TO trip_role;
GRANT USAGE ON SEQUENCE usertable_seq TO trip_role;
GRANT USAGE ON SEQUENCE tile_download_seq TO trip_role;
